use_default_settings: true

server:
  secret_key: "ad29332069110cfe642d3d17813d94c2"
  limiter: false
  image_proxy: false
  port: 8080
  bind_address: "0.0.0.0"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "de"

ui:
  default_locale: "de"
  default_theme: simple
